travis:
  secure:
    BINSTAR_TOKEN: UXjAy5GwJvDG4jFdf6pFsJizurIZg3F9N2GjBLWUpT7ElzjnxTcHLC4Asj2Th8TH0oTEj/HgNMVG7u9Z8Mg6w4KJx9xMYcG5DKzJft8ljHvM/rGlVmnT6/NTCFbqljUTMXuDZrCtjBooEgNKxUtPmk3cpsGQ2LgNZ6tEygetYHFRN4bMCJh9AUPAEO3ru0c13Nl14YkDVTBwQbcwCIqANY45LfGAXm4NrvKiPLbwOdpAqGhMRz9gJKsww+RVx7tglhIIRPU11NMePNh7gpOpqhyFDuRT+Ptet/rvtCwyK7/OG0GOjYB4WIGl8Y6Da8DDoTjWgiT+fevDbMKf+oX8avPqOVGkmYXPqjiucIoIrPC1KUHceX9Vr+j2KfoaMZYKTdbmC4dTktxGGmkGxXss7WWYx8WY3aQYN48h7AWXHlsLWky6B7/JwLV+xTfid3gCpdJNJED4l882lfVsppFvZSoWn+7zNi204fr4RQEEWTtDkWtTdR6FMwWf76ufF5PciVhvFnCS+6jzXUqBnCXVdRzQyJE1wr7HAIhuCbHdMnZ3pz9vo6ojQU+TrCCSbXNTR2hFHghSHvd6ZZiBjWn+/cAajsCw65gShqGiYJeyUqr4jnYDvbHpy1xlvGH+s8sKUT4ykY6yT2EXBssumS4w+bRzNvhScDiaUFPXNILnqKs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
